# 強制指定伺服器埠口
server.port=8080

# 資料庫設定：直接在雲端專案目錄下生成一個輕量資料庫檔案 (miniclinic.db)
spring.datasource.url=jdbc:sqlite:miniclinic.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect

# 每次重啟都重新初始化表格與資料
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
